// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/clustergarage/janus-proto/golang (interfaces: JanusdClient,Janusd_GetWatchStateClient)

// Package mock_golang is a generated GoMock package.
package mock_golang

import (
	context "context"
	golang "github.com/clustergarage/janus-proto/golang"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockJanusdClient is a mock of JanusdClient interface
type MockJanusdClient struct {
	ctrl     *gomock.Controller
	recorder *MockJanusdClientMockRecorder
}

// MockJanusdClientMockRecorder is the mock recorder for MockJanusdClient
type MockJanusdClientMockRecorder struct {
	mock *MockJanusdClient
}

// NewMockJanusdClient creates a new mock instance
func NewMockJanusdClient(ctrl *gomock.Controller) *MockJanusdClient {
	mock := &MockJanusdClient{ctrl: ctrl}
	mock.recorder = &MockJanusdClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockJanusdClient) EXPECT() *MockJanusdClientMockRecorder {
	return m.recorder
}

// CreateWatch mocks base method
func (m *MockJanusdClient) CreateWatch(arg0 context.Context, arg1 *golang.JanusdConfig, arg2 ...grpc.CallOption) (*golang.JanusdHandle, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWatch", varargs...)
	ret0, _ := ret[0].(*golang.JanusdHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWatch indicates an expected call of CreateWatch
func (mr *MockJanusdClientMockRecorder) CreateWatch(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWatch", reflect.TypeOf((*MockJanusdClient)(nil).CreateWatch), varargs...)
}

// DestroyWatch mocks base method
func (m *MockJanusdClient) DestroyWatch(arg0 context.Context, arg1 *golang.JanusdConfig, arg2 ...grpc.CallOption) (*golang.Empty, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DestroyWatch", varargs...)
	ret0, _ := ret[0].(*golang.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DestroyWatch indicates an expected call of DestroyWatch
func (mr *MockJanusdClientMockRecorder) DestroyWatch(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyWatch", reflect.TypeOf((*MockJanusdClient)(nil).DestroyWatch), varargs...)
}

// GetWatchState mocks base method
func (m *MockJanusdClient) GetWatchState(arg0 context.Context, arg1 *golang.Empty, arg2 ...grpc.CallOption) (golang.Janusd_GetWatchStateClient, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWatchState", varargs...)
	ret0, _ := ret[0].(golang.Janusd_GetWatchStateClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWatchState indicates an expected call of GetWatchState
func (mr *MockJanusdClientMockRecorder) GetWatchState(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchState", reflect.TypeOf((*MockJanusdClient)(nil).GetWatchState), varargs...)
}

// MockJanusd_GetWatchStateClient is a mock of Janusd_GetWatchStateClient interface
type MockJanusd_GetWatchStateClient struct {
	ctrl     *gomock.Controller
	recorder *MockJanusd_GetWatchStateClientMockRecorder
}

// MockJanusd_GetWatchStateClientMockRecorder is the mock recorder for MockJanusd_GetWatchStateClient
type MockJanusd_GetWatchStateClientMockRecorder struct {
	mock *MockJanusd_GetWatchStateClient
}

// NewMockJanusd_GetWatchStateClient creates a new mock instance
func NewMockJanusd_GetWatchStateClient(ctrl *gomock.Controller) *MockJanusd_GetWatchStateClient {
	mock := &MockJanusd_GetWatchStateClient{ctrl: ctrl}
	mock.recorder = &MockJanusd_GetWatchStateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockJanusd_GetWatchStateClient) EXPECT() *MockJanusd_GetWatchStateClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method
func (m *MockJanusd_GetWatchStateClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockJanusd_GetWatchStateClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockJanusd_GetWatchStateClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockJanusd_GetWatchStateClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).Context))
}

// Header mocks base method
func (m *MockJanusd_GetWatchStateClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockJanusd_GetWatchStateClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).Header))
}

// Recv mocks base method
func (m *MockJanusd_GetWatchStateClient) Recv() (*golang.JanusdHandle, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*golang.JanusdHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockJanusd_GetWatchStateClientMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).Recv))
}

// RecvMsg mocks base method
func (m *MockJanusd_GetWatchStateClient) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockJanusd_GetWatchStateClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method
func (m *MockJanusd_GetWatchStateClient) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockJanusd_GetWatchStateClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method
func (m *MockJanusd_GetWatchStateClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockJanusd_GetWatchStateClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockJanusd_GetWatchStateClient)(nil).Trailer))
}
