// Code generated by protoc-gen-go. DO NOT EDIT.
// source: janus.proto

package janus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JanusdConfig struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeName             string                 `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	PodName              string                 `protobuf:"bytes,3,opt,name=podName,proto3" json:"podName,omitempty"`
	Pid                  []int32                `protobuf:"varint,4,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	Cid                  []string               `protobuf:"bytes,5,rep,name=cid,proto3" json:"cid,omitempty"`
	Subject              []*JanusWatcherSubject `protobuf:"bytes,6,rep,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *JanusdConfig) Reset()         { *m = JanusdConfig{} }
func (m *JanusdConfig) String() string { return proto.CompactTextString(m) }
func (*JanusdConfig) ProtoMessage()    {}
func (*JanusdConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_janus_53bbb73dde66ad2a, []int{0}
}
func (m *JanusdConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JanusdConfig.Unmarshal(m, b)
}
func (m *JanusdConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JanusdConfig.Marshal(b, m, deterministic)
}
func (dst *JanusdConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JanusdConfig.Merge(dst, src)
}
func (m *JanusdConfig) XXX_Size() int {
	return xxx_messageInfo_JanusdConfig.Size(m)
}
func (m *JanusdConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_JanusdConfig.DiscardUnknown(m)
}

var xxx_messageInfo_JanusdConfig proto.InternalMessageInfo

func (m *JanusdConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JanusdConfig) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *JanusdConfig) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *JanusdConfig) GetPid() []int32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *JanusdConfig) GetCid() []string {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *JanusdConfig) GetSubject() []*JanusWatcherSubject {
	if m != nil {
		return m.Subject
	}
	return nil
}

type JanusWatcherSubject struct {
	Allow                []string `protobuf:"bytes,1,rep,name=allow,proto3" json:"allow,omitempty"`
	Deny                 []string `protobuf:"bytes,2,rep,name=deny,proto3" json:"deny,omitempty"`
	Event                []string `protobuf:"bytes,3,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JanusWatcherSubject) Reset()         { *m = JanusWatcherSubject{} }
func (m *JanusWatcherSubject) String() string { return proto.CompactTextString(m) }
func (*JanusWatcherSubject) ProtoMessage()    {}
func (*JanusWatcherSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_janus_53bbb73dde66ad2a, []int{1}
}
func (m *JanusWatcherSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JanusWatcherSubject.Unmarshal(m, b)
}
func (m *JanusWatcherSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JanusWatcherSubject.Marshal(b, m, deterministic)
}
func (dst *JanusWatcherSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JanusWatcherSubject.Merge(dst, src)
}
func (m *JanusWatcherSubject) XXX_Size() int {
	return xxx_messageInfo_JanusWatcherSubject.Size(m)
}
func (m *JanusWatcherSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_JanusWatcherSubject.DiscardUnknown(m)
}

var xxx_messageInfo_JanusWatcherSubject proto.InternalMessageInfo

func (m *JanusWatcherSubject) GetAllow() []string {
	if m != nil {
		return m.Allow
	}
	return nil
}

func (m *JanusWatcherSubject) GetDeny() []string {
	if m != nil {
		return m.Deny
	}
	return nil
}

func (m *JanusWatcherSubject) GetEvent() []string {
	if m != nil {
		return m.Event
	}
	return nil
}

type JanusdHandle struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	Pid                  []int32  `protobuf:"varint,3,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	ProcessEventfd       []int32  `protobuf:"varint,4,rep,packed,name=processEventfd,proto3" json:"processEventfd,omitempty"`
	MqFd                 int32    `protobuf:"varint,5,opt,name=mqFd,proto3" json:"mqFd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JanusdHandle) Reset()         { *m = JanusdHandle{} }
func (m *JanusdHandle) String() string { return proto.CompactTextString(m) }
func (*JanusdHandle) ProtoMessage()    {}
func (*JanusdHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_janus_53bbb73dde66ad2a, []int{2}
}
func (m *JanusdHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JanusdHandle.Unmarshal(m, b)
}
func (m *JanusdHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JanusdHandle.Marshal(b, m, deterministic)
}
func (dst *JanusdHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JanusdHandle.Merge(dst, src)
}
func (m *JanusdHandle) XXX_Size() int {
	return xxx_messageInfo_JanusdHandle.Size(m)
}
func (m *JanusdHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_JanusdHandle.DiscardUnknown(m)
}

var xxx_messageInfo_JanusdHandle proto.InternalMessageInfo

func (m *JanusdHandle) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *JanusdHandle) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *JanusdHandle) GetPid() []int32 {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *JanusdHandle) GetProcessEventfd() []int32 {
	if m != nil {
		return m.ProcessEventfd
	}
	return nil
}

func (m *JanusdHandle) GetMqFd() int32 {
	if m != nil {
		return m.MqFd
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_janus_53bbb73dde66ad2a, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JanusdConfig)(nil), "janus.JanusdConfig")
	proto.RegisterType((*JanusWatcherSubject)(nil), "janus.JanusWatcherSubject")
	proto.RegisterType((*JanusdHandle)(nil), "janus.JanusdHandle")
	proto.RegisterType((*Empty)(nil), "janus.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JanusdClient is the client API for Janusd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JanusdClient interface {
	CreateWatch(ctx context.Context, in *JanusdConfig, opts ...grpc.CallOption) (*JanusdHandle, error)
	DestroyWatch(ctx context.Context, in *JanusdConfig, opts ...grpc.CallOption) (*Empty, error)
	GetWatchState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Janusd_GetWatchStateClient, error)
}

type janusdClient struct {
	cc *grpc.ClientConn
}

func NewJanusdClient(cc *grpc.ClientConn) JanusdClient {
	return &janusdClient{cc}
}

func (c *janusdClient) CreateWatch(ctx context.Context, in *JanusdConfig, opts ...grpc.CallOption) (*JanusdHandle, error) {
	out := new(JanusdHandle)
	err := c.cc.Invoke(ctx, "/janus.Janusd/CreateWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *janusdClient) DestroyWatch(ctx context.Context, in *JanusdConfig, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/janus.Janusd/DestroyWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *janusdClient) GetWatchState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Janusd_GetWatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Janusd_serviceDesc.Streams[0], "/janus.Janusd/GetWatchState", opts...)
	if err != nil {
		return nil, err
	}
	x := &janusdGetWatchStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Janusd_GetWatchStateClient interface {
	Recv() (*JanusdHandle, error)
	grpc.ClientStream
}

type janusdGetWatchStateClient struct {
	grpc.ClientStream
}

func (x *janusdGetWatchStateClient) Recv() (*JanusdHandle, error) {
	m := new(JanusdHandle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JanusdServer is the server API for Janusd service.
type JanusdServer interface {
	CreateWatch(context.Context, *JanusdConfig) (*JanusdHandle, error)
	DestroyWatch(context.Context, *JanusdConfig) (*Empty, error)
	GetWatchState(*Empty, Janusd_GetWatchStateServer) error
}

func RegisterJanusdServer(s *grpc.Server, srv JanusdServer) {
	s.RegisterService(&_Janusd_serviceDesc, srv)
}

func _Janusd_CreateWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JanusdConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JanusdServer).CreateWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janus.Janusd/CreateWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JanusdServer).CreateWatch(ctx, req.(*JanusdConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Janusd_DestroyWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JanusdConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JanusdServer).DestroyWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janus.Janusd/DestroyWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JanusdServer).DestroyWatch(ctx, req.(*JanusdConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Janusd_GetWatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JanusdServer).GetWatchState(m, &janusdGetWatchStateServer{stream})
}

type Janusd_GetWatchStateServer interface {
	Send(*JanusdHandle) error
	grpc.ServerStream
}

type janusdGetWatchStateServer struct {
	grpc.ServerStream
}

func (x *janusdGetWatchStateServer) Send(m *JanusdHandle) error {
	return x.ServerStream.SendMsg(m)
}

var _Janusd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "janus.Janusd",
	HandlerType: (*JanusdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWatch",
			Handler:    _Janusd_CreateWatch_Handler,
		},
		{
			MethodName: "DestroyWatch",
			Handler:    _Janusd_DestroyWatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWatchState",
			Handler:       _Janusd_GetWatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "janus.proto",
}

func init() { proto.RegisterFile("janus.proto", fileDescriptor_janus_53bbb73dde66ad2a) }

var fileDescriptor_janus_53bbb73dde66ad2a = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x65, 0x18, 0x0a, 0x8f, 0x0b, 0xef, 0xe5, 0x65, 0x78, 0x8b, 0x09, 0xab, 0xa6, 0x8b, 0x97,
	0xae, 0x88, 0x01, 0x63, 0xe2, 0x1a, 0x51, 0xe3, 0xc2, 0x45, 0x89, 0x71, 0x3d, 0x74, 0x2e, 0x0a,
	0x81, 0x99, 0xda, 0x0e, 0x1a, 0x7e, 0xc3, 0x2f, 0x31, 0x7e, 0xa1, 0x99, 0x5b, 0x40, 0x31, 0xe0,
	0xee, 0x9c, 0x73, 0xcf, 0xe4, 0xde, 0x73, 0x5a, 0x68, 0xcd, 0x95, 0x59, 0x15, 0xbd, 0x2c, 0xb7,
	0xce, 0x8a, 0x80, 0x48, 0xf4, 0xce, 0xa0, 0x7d, 0xe3, 0x91, 0x1e, 0x5a, 0x33, 0x9d, 0x3d, 0x08,
	0x01, 0x35, 0xa3, 0x96, 0x28, 0x59, 0xc8, 0xe2, 0x66, 0x42, 0x58, 0x74, 0xe1, 0x97, 0xb1, 0x1a,
	0x6f, 0xbd, 0x5e, 0x25, 0x7d, 0xc7, 0x85, 0x84, 0x46, 0x66, 0x35, 0x8d, 0x38, 0x8d, 0xb6, 0x54,
	0xfc, 0x05, 0x9e, 0xcd, 0xb4, 0xac, 0x85, 0x3c, 0x0e, 0x12, 0x0f, 0xbd, 0x92, 0xce, 0xb4, 0x0c,
	0x42, 0x1e, 0x37, 0x13, 0x0f, 0xc5, 0x29, 0x34, 0x8a, 0xd5, 0x64, 0x8e, 0xa9, 0x93, 0xf5, 0x90,
	0xc7, 0xad, 0x7e, 0xb7, 0x57, 0x1e, 0x49, 0x37, 0xdd, 0x2b, 0x97, 0x3e, 0x62, 0x3e, 0x2e, 0x1d,
	0xc9, 0xd6, 0x1a, 0xdd, 0x41, 0xe7, 0xc0, 0x5c, 0xfc, 0x83, 0x40, 0x2d, 0x16, 0xf6, 0x45, 0x32,
	0x5a, 0x50, 0x12, 0x1f, 0x48, 0xa3, 0x59, 0xcb, 0x2a, 0x89, 0x84, 0xbd, 0x13, 0x9f, 0xd1, 0x38,
	0xc9, 0x4b, 0x27, 0x91, 0xe8, 0x75, 0xd7, 0xc5, 0xb5, 0x32, 0x7a, 0xb1, 0x9f, 0x9b, 0x1d, 0xcf,
	0x5d, 0x3d, 0x98, 0x9b, 0x7f, 0xe6, 0xfe, 0x0f, 0x7f, 0xb2, 0xdc, 0xa6, 0x58, 0x14, 0x23, 0xbf,
	0x68, 0xba, 0x2d, 0xe5, 0x9b, 0xea, 0x4f, 0x5d, 0x3e, 0x5d, 0xfa, 0x82, 0x58, 0x1c, 0x24, 0x84,
	0xa3, 0x06, 0x04, 0xa3, 0x65, 0xe6, 0xd6, 0xfd, 0x37, 0x06, 0xf5, 0xf2, 0x3a, 0x71, 0x0e, 0xad,
	0x61, 0x8e, 0xca, 0x21, 0x15, 0x20, 0x3a, 0x5f, 0x3b, 0xdb, 0x7c, 0xc7, 0xee, 0xbe, 0x58, 0x06,
	0x8a, 0x2a, 0x62, 0x00, 0xed, 0x0b, 0x2c, 0x5c, 0x6e, 0xd7, 0x3f, 0xbc, 0x6d, 0x6f, 0x44, 0x5a,
	0x1c, 0x55, 0xc4, 0x19, 0xfc, 0xbe, 0x42, 0x47, 0x0f, 0xc6, 0x4e, 0x39, 0x14, 0x7b, 0x86, 0x23,
	0xab, 0x4e, 0xd8, 0xa4, 0x4e, 0xbf, 0xda, 0xe0, 0x23, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xa6, 0xfa,
	0x62, 0x79, 0x02, 0x00, 0x00,
}
